sf_eviction_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_NAME_DEV') }}"
      threads: 4
      priority: interactive
      keyfile: /home/sanyashireen/.google/credentials/google_credentials.json
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_NAME_PROD') }}"
      threads: 4
      priority: interactive
      keyfile: /home/sanyashireen/.google/credentials/google_credentials.json