version: 2

sources:
  # just any name we like to name source
  - name: staging
  # refers to a project in BQ
    database: '{{ var("GCP_PROJECT_ID") }}'
    schema: '{{ var("BQ_DATASET_NAME") }}'

    tables:
      - name: '{{ var("BQ_TABLE_NAME_EVICTION") }}'